name = "kasaglowclean-aistudio"
pages_build_output_dir = "dist"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kasaglow-submissions"
database_id = "4b729739-978c-41ac-af74-7ad8df3b943d"

[vars]
SITE_URL = "https://kasaglowclean.com"
PAYPAL_ENV = "sandbox"
STRIPE_PUBLIC_KEY = "pk_live_xxxxxxxxxx"
RESEND_API_KEY = "re_Q6shyEbe_KBz6PPtKCUshy8z6B4jsk6V8"
ADMIN_SECRET = "password123"
